// import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import {GlobalContextProvider} from "@/assets/providers/GlobalProvider"

import "../assets/scss/index.scss"
import Header from "./header"
import Footer from "./footer"
import {getAllProfiles,getAllPosts,getAllDatas} from "@/lib/prisma"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const tmp = await getAllProfiles()
  return (
    <html lang="fr">
      <body className={inter.className}>
      <ClerkProvider>
        <GlobalContextProvider>
          <Header />
            {JSON.stringify(tmp)}
            <hr/>
            {children}
          <Footer />
        </GlobalContextProvider>
      </ClerkProvider>
      </body>
    </html>
  )
}
