
import { createGlobalStyle } from 'styled-components'
import { Inter, Montserrat} from 'next/font/google'
// import { ClerkProvider } from '@clerk/nextjs'
// import {DarkModeProvider} from "./providers"
// import {GlobalContextProvider} from "../assets/utils/globalContext"//
import Header from "./header"
import Footer from "./footer"
import "../assets/scss/index.scss"



const inter = Inter({ subsets: ['latin'] })
// , ff = Montserrat({
//   subsets: ['latin']
//   , weight: ["300", "400", "600", "700", "800", "900", ]
//   , style: ["normal", "italic"]
//   // , variable: "--font-monserrat_aaaa" //COPIED FROM A NEXTJS TUTO
// })



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      {/* <ClerkProvider> */}
        <body className={` ${inter.className}`}>
          {/* <DarkModeProvider> //*/}
          {/* <GlobalContextProvider> //*/}
            <Header />
              {children}
            <Footer />
          {/* </GlobalContextProvider> //*/}
          {/* </DarkModeProvider> //*/}
        </body>
      {/* </ClerkProvider> */}
    </html>
  )
}


